#mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjf?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: null

  #session配置
  session:
    store-type: redis
    timeout: 30S



  #redis配置
  redis:
    host: localhost
    port: 6379

  #activeMq
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

    pool:
      max-connections: 10

    packages:
      trust-all: true #信任所有包


  #mq消息模式，true：topic模式，false：队列模式
  jms:
    pub-sub-domain: true





mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000
  tomcat:
    threads:
      max: 3

test:
  name: sxxx
  ages:
    - 13.4
    - 14.5
    - 2.6




